### ISSUE TITLE
Uninstall Extension from UI

### ISSUE THREAD

**Issue by Semiotikal** [amphi-ai/amphi-etl#155]
Hi there,

I installed the amphi-etl extension in my local Jupyterlab to experiment but now wish to uninstall it. However, the amphi-etl UI changes to jupyterlab mean there is no extensions manager available in the UI for me to disable amphi-etl. Running pip uninstall and conda uninstall from the terminal also didn't remove the extension.

I would recommend either enabling the extensions manager in amphi-etl or configure a custom uninstall or disable feature as this is rather frustrating as an end user.

**Comment by tgourdel** [comment]
Hi @Semiotikal,

I'm sorry you encounter this issue. There is a misunderstanding (probably due to the fact it isn't clear) because if you want to add Amphi to Jupyterlab, you need to install "jupyterlab-amphi" from the extension manager and not amphi-etl. Unfortunately, amphi-etl appears in the extension manager, and amphi-etl is a JupyterLab distribution in itself (not just an extension), that is why you get a lot of things removed from JupyterLab while jupyterlab-amphi just add the pipeline editor basically.

I'll look at removing amphi-etl from the extension manager to avoid this issue. In your case, do you use a virtual environment?
