### ISSUE TITLE
A formula transformation tool

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#27]
Hello,

 I would like to have a formula tool with these features (looks very classic):
 -modify an existing column or create a new one
 -if a new one, ability to set the type (with a dropdown menu as exemple)
 -autocompletion
 -preview
-ability to disable a formula (not usual but when developing, it's pretty cool)
 -language should be python of course
 
 For reference, the Alteryx formula
 
![image](https://github.com/amphi-ai/amphi-etl/assets/46959192/c650d6fa-4a24-40e5-b9f4-3afcf83f7ba3)

Best regards,

Simon

**Comment by tgourdel** [comment]
Hi Simon,
That's a good idea. I do believe this can be done with custom code component but I see why it would help to have one and probably easier for people less comfortable with Python. I probably can have an experimental version of this pretty quick!
Thanks for the suggestion!!

**Comment by tgourdel** [comment]
Introduced the formula component in 0.5.7:
![image](https://github.com/user-attachments/assets/adb9028f-08e0-4182-875c-a6c0b0f6dae3)
Multiple modes:
Python Expression
Python Function
Lambda Expression

Haven't done the documentation yet, but will do asap
![image](https://github.com/user-attachments/assets/24350004-3d94-4e9c-af42-d6eff10c90c6)

Keeping open because still need to be done:
-color highlighting
- auto completion

**Comment by simonaubertbd** [comment]
@tgourdel I was thinking : wouldn't it be smarter if I split this issue in two and I create two other ones for color highlighting or autocompletion?

**Comment by tgourdel** [comment]
Sure, that's a good idea. Especially because the highlighting and auto-complete are part of a larger work that for all the code inputs (python code, sql inputs).

**Comment by simonaubertbd** [comment]
@tgourdel Done. I think you can close this issue now.
