### ISSUE TITLE
Sheets of excel files are retrieved badly

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#29]
Hello,

Excel file in attachment
[BD_Market.xlsx](https://github.com/user-attachments/files/15883649/BD_Market.xlsx)

path : OneDrive - Business & Decision/B&D_Market_20190423/5_Small_Data/FR/BD_Market.xlsx

Result : 
![image](https://github.com/amphi-ai/amphi-etl/assets/46959192/34db9a73-1d68-4d98-abad-cf841b516484)

**Comment by tgourdel** [comment]
Well, that's just bad design from myself. It doesn't retrieve the sheets from the file, it's just options you can select, 0 being the first one, 1t is a typo which should be 1 and the second sheet... and the third is an example of how to select multiple ones because you can also "Add an item" with a custom choice. Obviously it's not clear at all and need to find a better way.

**Comment by simonaubertbd** [comment]
@tgourdel Ah, that makes sense now. Maybe changing just above Sheets by Sheets N° would help. 😆

**Comment by tgourdel** [comment]
Mitigated with better labels for now. Will have to come back to and improve
`pip install --upgrade --force-reinstall amphi-etl`
