### ISSUE TITLE
A connection and credentials manager

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#48]
Hello,

Instead of always writing credentials and connections settings, it would be cool to store it in a manager (of course,not in clear ^^)

Best regards,

Simon

**Comment by tgourdel** [comment]
Yes, it's in the works, have started working on it :)

**Comment by tgourdel** [comment]
The approach I've taken for now is to allow the use of environment variables from .env files. Cloud credential managers will come in the short term with AWS secret manager.
Something to test maybe is the integration with laptop credential managers with https://github.com/jaraco/keyring.

In terms of connections, starting in the 5.0.0 release you'll be able to create connections and save them as components so that you can reuse them across pipelines.
Stay tune :)
