### ISSUE TITLE
Weird message

### ISSUE THREAD

**Issue by rapidarchitect** [amphi-ai/amphi-etl#58]
getting this with every execution, the pipeline works so not sure what this is about

ERROR: You must give at least one requirement to install (see "pip help install")

**Comment by tgourdel** [comment]
Hi @rapidarchitect, this error or most likely warning happens with some components when it's trying but fail to install a particular library. It's usually just a warning. If you could tell me what were the components you used in your pipeline I could check which components is giving this warning and fix it.
In most cases it doesn't impact the pipelines since it's due to library checks and installation but it'd be better for the experience to remove those unnecessary error messages.
Thanks for reporting!
Thibaut

**Comment by rapidarchitect** [comment]
It’s the rest input component

___________________________
Mike Hjorleifsson
***@***.***

This e-mail and any files transmitted with it are confidential and are intended solely for the use of the
individual entity to whom they are addressed. This communication may contain material protected by the
attorney-client privilege. If you are not the intended recipient or the person responsible for delivering the
e-mail to the intended recipient, be advised that you have received this e-mail in error and that any use,
dissemination, forwarding, printing or copying this e-mail or any file or files transmitted with it is strictly prohibited.

**Comment by tgourdel** [comment]
Thanks @rapidarchitect, I found the issue and fixed it. Will be in next release!
